### ISSUE TITLE
WebExtension?

### ISSUE THREAD

**Issue by bintoro** [arantius/uppity#2]
Any plans to turn this one into a WebExtension? According to AMO, Uppity has ~4000 users.

**Comment by XRolland** [comment]
+1! Thanks for this so easy to use extension. Is it possible to tur it to WebExt?

**Comment by gizmecano** [comment]
This issue seems to be resolved by the [last official release](https://addons.mozilla.org/fr/firefox/addon/uppity/versions/?page=1#version-2.0) (which [omits some previous options](https://github.com/arantius/uppity/issues/3) right now, _because WebExt APIs are awful and broken_).
