### ISSUE TITLE
Middle-click to open in new tap no longer works

### ISSUE THREAD

**Issue by lkmorlan** [arantius/uppity#4]
Prior to the WebExtension rewrite, middle-click on the Uppity button on the toolbar would open the parent page in a new tab. This no longer works.

**Comment by arantius** [comment]
Welcome to WebExtensions!  Our UI options are absurdly narrow.  Nothing I can do about this.

**Comment by lkmorlan** [comment]
Gack! That is horrible. Anyway, thanks for your persistence in making Uppity do as much as it can.

**Comment by allanlaal** [comment]
upstream blocker fixed now: https://bugzilla.mozilla.org/show_bug.cgi?id=1469148
