### ISSUE TITLE
Place Uppity in the location bar

### ISSUE THREAD

**Issue by davidhedlund** [arantius/uppity#7]
I'm sure that the ideal position for Uppity would be in the location bar since it handles the URL in it.

**Comment by arantius** [comment]
Being a toolbar button lets you move it into the overflow, and not normally see it.  I don't know if you get that choice with a page action.

**Comment by davidhedlund** [comment]
> Being a toolbar button lets you move it into the overflow, and not normally see it.

I always want to see it so I don't forget to use it.

> I don't know if you get that choice with a page action.

Can you please explain more about this?

**Comment by davidhedlund** [comment]
No you cannot use "Pin to Overflow Menu" for location bar buttons (eg [CanvasBlocker](https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/)).

**Comment by davidhedlund** [comment]
But if you place Uppity in the overflow menu, then it will take two steps to click on it 1) click on the overflow menu 2) click on Uppity. Using Uppity this way wouldn't be more effective than 1) click at the end of the URL in the on the location bar 2) press Ctrl+backspace.

**Comment by arantius** [comment]
I tend to use the keyboard shortcut.

**Comment by davidhedlund** [comment]
@arantius That's a very good command. I suggested this here:
> Feature request: Alt + up arrow = Navigate up one directory level - https://bugzilla.mozilla.org/show_bug.cgi?id=1432127
